-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, BS.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM AUTHOR A
JOIN (SELECT B.AUTHOR_ID, SUM(S.SALES) * B.PRICE AS SALES, B.CATEGORY
     FROM BOOK_SALES S
     JOIN BOOK B
     ON S.BOOK_ID = B.BOOK_ID
     WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
     GROUP BY B.BOOK_ID) BS
ON BS.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_ID, BS.CATEGORY 
ORDER BY A.AUTHOR_ID ASC, BS.CATEGORY DESC;