-- 코드를 작성해주세요
SELECT F.ID, N.FISH_NAME, F.LENGTH 
FROM FISH_INFO F
JOIN FISH_NAME_INFO N
ON F.FISH_TYPE = N.FISH_TYPE
WHERE ID IN (SELECT ID
            FROM FISH_INFO
            JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
                       FROM FISH_INFO
                       GROUP BY FISH_TYPE) M
             ON FISH_INFO.FISH_TYPE = M.FISH_TYPE 
             AND FISH_INFO.LENGTH = M.LENGTH)